import type { Metadata } from "next";
import { Open_Sans, Manrope } from "next/font/google";
import '@/styles/styles.scss'


const openSans = Open_Sans({
  weight: ["800"],
  style: ["italic"],
  subsets: ["latin", "cyrillic"],
  variable: "--font-open-sans",
});

const manrope = Manrope({
  weight: ["500", "600", "700"],
  style: ["normal"],
  subsets: ["latin", "cyrillic"],
  variable: "--font-manrope",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${openSans.variable} ${manrope.variable}`}>
        {children}
      </body>
    </html>
  );
}
